### ISSUE TITLE
Add Pip support

### ISSUE THREAD

**Issue by wsvincent** [platformsh-templates/django4#14]
### What in this template can be improved or added as a feature?

It would be very helpful to have an official version of this with Pip support not just Pipenv. 

### What exactly should be updated?

Should be as simple as adding a `requirements.txt` file, updating the `build` commands in `platform.app.yaml` similar to what Eric has here: https://github.com/ehmatthes/django-simple-deploy/blob/main/simple_deploy/templates/platform.app.yaml

I guess mainly it'd be good to know if there's anything else that changes with Pip vs Pipenv. I would say anecdotally that Pip is far more common than Pipenv at this point in the Django community.

### How important is this feature to you?

It helps me move forward with confidence and recommend Platform.sh to others vs other hosting providers.

**Comment by chadwcarlson** [comment]
@wsvincent Thanks for the feedback! If that's the trend you've noticed, we'll be sure to make this change this week.

**Comment by chadwcarlson** [comment]
Makes sense. Out of curiosity, how have you found working with Poetry? Or is it largely not needed for your work and pip is enough?

**Comment by wsvincent** [comment]
Poetry is popular but more than I personally need for most stuff. I know @jefftriplett has thoughts on this as he says a wide array of patterns in the consulting world.

**Comment by jefftriplett** [comment]
If I were your company, I'd recommend having a solid Poetry path/story. It's popular enough and under-documented on other platforms, IMO. 

That said, I think pip is 100x more important than anything else. I think Poetry and pipenv are worthwhile.

**Comment by chadwcarlson** [comment]
Noted, and thank you both for the feedback. I don't think we would drop documentation for pipenv, and we'd like to add more Poetry as we're using it plenty internally. Pip first, document pipenv/poetry options 👍

**Comment by chadwcarlson** [comment]
@wsvincent @jefftriplett pip made as default, and poetry support added in https://github.com/platformsh-templates/django4/pull/16
